MODEL:
  BACKBONE:
    NAME: googlenet
  PRETRAIN: imagenet

SAVE_DIR: output-googlenet-cub

INPUT:
   MODE: 'RGB'
   PIXEL_MEAN: [0.485, 0.456, 0.406]
   PIXEL_STD: [0.229, 0.224, 0.225]

SOLVER:
  MAX_ITERS: 10000
  STEPS: [3000]
  OPTIMIZER_NAME: Adam
  BASE_LR: 0.00003
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.0005

LOSSES:
  DBML_LOSS:
    POS_A: 0.5
    POS_B: 0.5
    NEG_A: 1.0
    NEG_B: 0.01
    MARGIN: 0.1

DATA:
  TRAIN_IMG_SOURCE: resource/datasets/CUB_200_2011/train.txt
  TEST_IMG_SOURCE: resource/datasets/CUB_200_2011/test.txt
  TRAIN_BATCHSIZE: 60
  TEST_BATCHSIZE: 128
  NUM_WORKERS: 8
  NUM_INSTANCES: 5

VALIDATION:
  VERBOSE: 200
