MODEL:
  BACKBONE:
    NAME: bninception
  PRETRAIN: imagenet

SAVE_DIR: output-bninception-cub

SOLVER:
  MAX_ITERS: 5000
  STEPS: [1200]
  OPTIMIZER_NAME: Adam
  BASE_LR: 0.00003
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.0005

LOSSES:
  CBML_LOSS:
    POS_A: 0.5
    POS_B: 0.5
    NEG_A: 1.0
    NEG_B: 0.01
    MARGIN: 0.1
    HYPER_WEIGHT: 0.0
  
DATA:
  TRAIN_IMG_SOURCE: resource/datasets/CUB_200_2011/train.txt
  TEST_IMG_SOURCE: resource/datasets/CUB_200_2011/test.txt
  TRAIN_BATCHSIZE: 100
  TEST_BATCHSIZE: 128
  NUM_WORKERS: 8
  NUM_INSTANCES: 5

VALIDATION:
  VERBOSE: 200
